name: 'Challenge-case'
description: 'For the challenge to 16/01/2025 i need to create a lower case'
inputs:
  text:
    description: 'Input text needed for test'
    required: true
    default: 'Challenge for lowercase'
branding:
  icon: chevron-down # Utilisation de l'icone du projet du formateur pour ne pas a avoir d'autre résultat
  color: blue # On change la couleur pour avoir un peux de personnalité quand même

outputs:
  text:
    description: 'Le texte dans lower case'
    value: ${{ steps.lower-step.outputs.text }}
runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - name: Start to lower text ${{ inputs.text }}
      run: |
        chmod 777 lower.sh
        lower.sh 'text=${{ inputs.text }}' >> $GITHUB_OUTPUT
      shell: bash
      id: lower-step
