on:
  push:
    branches:
      - main
  pull_request:

# Création d'un jobs pour des action spécifique
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test checkout
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - name: Test output message
      uses: ./
      id: lowered
      with:
        text: |
          Hello the World of DevOps
    - name: Debug lowered message
      run: echo "${{ steps.lowered.outputs.text }}"

# Compréhension du code à revoir (pour moi) phase de test si j'ai bien compris (possible .github a changer en .github-test voir si y a un impact) 
